void mostradorLogo(void);
void digiteEnter(void);
bool verificaNumero(char teste);
bool validaCPF(const char *cpf);
bool verificaNome(const char *nome);
char *input(const char *entrada);
void recebeData();
bool validaData(const char *data);
bool validaValor(const char *dinheiro);
bool validaTelefone(char *fone);
bool validaHora(char horario[5]);